### ISSUE TITLE
Can't use sqloxide on python 3.13

### ISSUE THREAD

**Issue by rohanjain101** [wseaton/sqloxide#264]
```
>>> import sqloxide
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import sqloxide
  File "D:\ps_313\Lib\site-packages\sqloxide\__init__.py", line 1, in <module>
    from .sqloxide import *
ModuleNotFoundError: No module named 'sqloxide.sqloxide'
>>>
```

**Comment by wseaton** [comment]
3.13 wheels available for v0.1.51
